version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app

  socketserver:
    build: .
    command: ["python", "main.py"]
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
